{{- if .Values.pdb.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: backend-pdb
  labels:
    app: backend
    {{- include "todo-app.labels" . | nindent 4 }}
spec:
  minAvailable: {{ .Values.pdb.minAvailable }}
  selector:
    matchLabels:
      app: backend
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: auth-pdb
  labels:
    app: auth
    {{- include "todo-app.labels" . | nindent 4 }}
spec:
  minAvailable: {{ .Values.pdb.minAvailable }}
  selector:
    matchLabels:
      app: auth
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: client-pdb
  labels:
    app: client
    {{- include "todo-app.labels" . | nindent 4 }}
spec:
  minAvailable: {{ .Values.pdb.minAvailable }}
  selector:
    matchLabels:
      app: client
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: reverse-proxy-pdb
  labels:
    app: reverse-proxy
    {{- include "todo-app.labels" . | nindent 4 }}
spec:
  minAvailable: {{ .Values.pdb.minAvailable }}
  selector:
    matchLabels:
      app: reverse-proxy
{{- end }}
