name: CI Monorepo

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      backend: ${{ steps.filter.outputs.backend }}
      client: ${{ steps.filter.outputs.client }}
      auth: ${{ steps.filter.outputs.auth }}
    steps:
      - uses: actions/checkout@v7
      - uses: dorny/paths-filter@v4
        id: filter
        with:
          filters: |
            backend:
              - 'backend/**'
            client:
              - 'client/**'
            auth:
              - 'auth/**'

  backend:
    needs: changes
    if: ${{ needs.changes.outputs.backend == 'true' || github.event_name == 'push' }}
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-node@v7
        with:
          node-version: 22
          cache: npm
          cache-dependency-path: backend/package-lock.json
      - run: npm ci
      - run: npm run lint
      - run: npm run typecheck
      - run: npm run format-check
      - run: npm run build
      - run: npm run test:coverage

  client:
    needs: changes
    if: ${{ needs.changes.outputs.client == 'true' || github.event_name == 'push' }}
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: client
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-node@v7
        with:
          node-version: 22
          cache: npm
          cache-dependency-path: client/package-lock.json
      - run: npm ci
      - run: npm run lint
      - run: npm run typecheck
      - run: npm run format-check
      - run: npm run build
      - run: npm run test:coverage

  auth:
    needs: changes
    if: ${{ needs.changes.outputs.auth == 'true' || github.event_name == 'push' }}
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: auth
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-node@v7
        with:
          node-version: 22
          cache: npm
          cache-dependency-path: auth/package-lock.json
      - run: npm ci
      - run: npm run lint
      - run: npm run typecheck
      - run: npm run format-check
      - run: npm run build
      - run: npm run test:coverage

  ci-success:
    name: All CI Passed
    needs: [backend, client, auth]
    if: always()
    runs-on: ubuntu-latest
    steps:
      - name: Check dependencies status
        if: contains(needs.*.result, 'failure') || contains(needs.*.result, 'cancelled')
        run: |
          echo "Un des jobs CI a echoue."
          exit 1
